wultra/powerauth-server

pom.xml, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ApplicationServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/model/ServiceError.java
When fetching application detail, check if application exists.
Added extra ServiceError.
=> Fix #15: When fetching application detail, check if application exists

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/SignatureServiceBehavior.java
Evaluate the necessity to increment counter on server side in failed signatures.
=> Fix lime-company/powerauth-crypto#137

pom.xml, powerauth-java-client-axis/src/main/java/io/getlime/security/powerauth/soap/axis/client/PowerAuthServiceClient.java, powerauth-java-server/pom.xml, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/Application.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/ServletInitializer.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/configuration/AsyncTaskExecutorConfig.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/configuration/PowerAuthServiceConfiguration.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/configuration/WebServiceConfig.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/ActivationHistoryEntity.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/ActivationRecordEntity.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/ApplicationEntity.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/ApplicationVersionEntity.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/MasterKeyPairEntity.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/SignatureEntity.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/PowerAuthServiceImpl.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ApplicationServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/CallbackUrlBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/EncryptionServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/IntegrationBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/TokenBehavior.java, powerauth-java-server/src/main/resources/application.properties
Updated JavaDoc
Migrated AsyncRestTemplate to WebClient and @Async
=> Fix #60: Update Spring Boot to 2.0.0

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/configuration/WebApplicationConfig.java
One more change related to Spring boot 2.0.0 which I overlooked.
=> WebMvcConfigurerAdapter deprecation warning

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/Application.java
Note that this commit is only a temporary workaround until the root cause gets resolved in Spring boot project.
=> Fix #86: Duplicate log messages

powerauth-java-client-spring/pom.xml, powerauth-java-server/pom.xml, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/configuration/WebServiceConfig.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/integration/IntegrationUserDetailsService.java
It seems that the latest version of Spring WS-Security fixes the issue.
However, based on comments in [SWS-970](https://jira.spring.io/browse/SWS-970), we need to make sure that the code is not leaking memory. @romanstrobl, could you have a look and verify this is not the case? (I have more trust in your profiling skills...)
=> Fix #152: Investigate Spring-WS security latest version

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationServiceBehavior.java
The last remaining part of fixing https://github.com/wultra/powerauth-server/issues/160
=> Fix #160: Crypto 3.0: Activation status

docs/sql/mysql/create_schema.sql, docs/sql/oracle/create_schema.sql, docs/sql/postgresql/create_schema.sql, powerauth-java-client-axis/src/main/java/io/getlime/security/powerauth/soap/axis/client/PowerAuthServiceClient.java, powerauth-java-client-spring/src/main/java/io/getlime/security/powerauth/soap/spring/client/PowerAuthServiceClient.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/ActivationRecordEntity.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v2/ActivationServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/EciesEncryptionBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/model/request/ActivationLayer2Request.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/model/response/ActivationLayer2Response.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v3/PowerAuthServiceImpl.java
Changes in this pull request:
- Fix #159: Crypto 3.0: New activation
- Updated version of PowerAuth protocol in JavaDoc in Spring client
- Added field `ctr_data` to `ActivationRecordEntity`, counter data initialization in prepare step
=> Fix #159: Crypto 3.0: New activation

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/controller/RESTControllerAdvice.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationServiceBehavior.java
Updated logic for calculation of activation fingerprint.
=> Fix #212: Crypto 3.0: Update fingerprint for activations

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/converter/v3/ServerPrivateKeyConverter.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/ServiceBehaviorCatalogue.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v2/ActivationServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationHistoryServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/SignatureServiceBehavior.java
Few coverity scan issues were fixed. InitActivation switched to v3 to avoid code duplication.
=> Fix #214: Fix issues found by coverity scan

powerauth-java-client-axis/src/main/resources/soap/wsdl/service-v2.wsdl, powerauth-java-client-axis/src/main/resources/soap/wsdl/service-v3.wsdl, powerauth-java-client-spring/src/main/resources/soap/wsdl/service-v2.wsdl, powerauth-java-client-spring/src/main/resources/soap/wsdl/service-v3.wsdl, powerauth-java-server/src/main/resources/xsd/PowerAuth-2.0.xsd, powerauth-java-server/src/main/resources/xsd/PowerAuth-3.0.xsd
See issue for details: https://github.com/wultra/powerauth-server/issues/228
=> Fix #228: Fix Axis issues found using automated tests

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/controller/v3/PowerAuthController.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/endpoint/v3/PowerAuthEndpoint.java
This pull request unifies the REST and SOAP interfaces and fixes small typos and differences found when comparing the interface methods.
=> Fix #234: Method getEciesDecryptor is missing in REST controller

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationServiceBehavior.java
Pull request contains following changes:
- Add counter data to encrypted status blob
- Fix of generating random status blobs (blob size should be 32, not 16)
=> Fix #242: Crypto 3.0: Add counter data to encrypted status blob

README.md, docs/Axis-1-Support-(Deprecated).md, docs/Configuring-SOAP-Client-for-Axis2.md, docs/Configuring-SOAP-Client-for-Spring.md, docs/Database-Structure.md, docs/Deploying-PowerAuth-Server.md, docs/Encrypting-Records-in-Database.md, docs/Home.md, docs/Installing-Bouncy-Castle.md, docs/Migration-Instructions.md, docs/Offline-Signatures.md, docs/PowerAuth-Server-0.18.0.md, docs/PowerAuth-Server-0.19.0.md, docs/PowerAuth-Server-0.21.0.md, docs/SOAP-Client-Library-Usage.md, docs/SOAP-Method-Compatibility.md, docs/SOAP-Service-Methods.md, docs/Server-Error-Codes.md, docs/System-Requirements.md, docs/Using-SOAP-Service-Client.md
I will reopen the pull request on documentation brach, @hvge if you find more issues, let me know and I will fix them.
=> Migrate documentation from wiki to code

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/SignatureServiceBehavior.java
We need to update the 0.21.0 release due to Wildfly startup issue caused by Spring boot minor version upgrade.
=> Update release 0.21.0

docs/Deploying-PowerAuth-Server.md, docs/Installing-Bouncy-Castle.md, docs/PowerAuth-Server-0.22.0.md, pom.xml, powerauth-java-client-axis/pom.xml, powerauth-java-client-spring/pom.xml, powerauth-java-server/pom.xml, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/configuration/PowerAuthServiceConfiguration.java
This pull request contains following changes:
- Fix #274: Support for Java 11
- Updated version to 0.22.0
- Spring boot dependency updated to 2.1.2.RELEASE
- Updated BC dependency
=> Fix #274: Support for Java 11

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/configuration/PowerAuthServiceConfiguration.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/CallbackUrlBehavior.java, powerauth-java-server/src/main/resources/application.properties
The configuration of HTTP proxy and timeout is similar to Push Server.
=> Fix #147: Make WebClient instantiation configurable

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/ActivationHistoryEntity.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/ApplicationEntity.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/ApplicationVersionEntity.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/MasterKeyPairEntity.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/RecoveryCodeEntity.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/RecoveryConfigEntity.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/RecoveryPukEntity.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/SignatureEntity.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/RecoveryServiceBehavior.java
Fix dead store issues found by coverity scan.
=> Fix issues found by coverity scan

README.md, docs/Encrypting-Records-in-Database.md, docs/Installing-Bouncy-Castle.md, docs/PowerAuth-Server-0.22.0.md, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/RecoveryServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/UpgradeServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/model/TokenInfo.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/model/request/ActivationLayer2Request.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/model/request/VaultUnlockRequestPayload.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/model/response/ActivationLayer2Response.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/model/response/ConfirmRecoveryResponsePayload.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/model/response/UpgradeResponsePayload.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/model/response/VaultUnlockResponsePayload.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/model/signature/OfflineSignatureRequest.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/model/signature/OnlineSignatureRequest.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/model/signature/SignatureData.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/model/signature/SignatureResponse.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v3/PowerAuthServiceImpl.java
- Added constructors for model classes
- Updated documentation
- Updated release version
=> Code cleanup before release

docs/Installing-Bouncy-Castle.md
This pull request fixes documentation of Bouncy Castle configuration on JBoss.
=> Fix #332: Update documentation for Bouncy Castle deployment on JBoss

docs/Encrypting-Records-in-Database.md, docs/Using-HashiCorp-Vault.md, docs/_Sidebar.md, pom.xml, powerauth-java-server/pom.xml, powerauth-java-server/src/main/resources/bootstrap.properties
The integration actually seems relatively straight forward. The most difficult part was to understand loading priorities of Spring Boot app (`bootstrap.properties` vs. `application.properties`) and to get the naming conventions of the Vault storage right.
The main part of this PR is the documentation - please read it carefully and try to follow it while testing.
=> Fix #76: Investigate Spring Vault

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/configuration/PowerAuthServiceConfiguration.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationServiceBehavior.java
This change also adding a basic validation to PowerAuthServiceConfiguration
=> Fix #354: Look ahead constant is part of status blob

docs/PowerAuth-Server-0.23.0.md
Related to wultra/powerauth-crypto#293
=> Docs: Added info about changed DB encryption to migration guide

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/configuration/PowerAuthServiceConfiguration.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v3/PowerAuthServiceImpl.java, powerauth-java-server/src/main/resources/application.properties
=> Fix #363: Add configuration enabling biometry in vault unlock.

docs/SOAP-Service-Methods.md, powerauth-java-client-axis/src/main/java/io/getlime/security/powerauth/soap/axis/client/PowerAuthServiceClient.java, powerauth-java-client-axis/src/main/resources/soap/wsdl/serviceV3.wsdl, powerauth-java-client-spring/src/main/java/io/getlime/security/powerauth/soap/spring/client/PowerAuthServiceClient.java, powerauth-java-client-spring/src/main/resources/soap/wsdl/serviceV3.wsdl, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/controller/v3/PowerAuthController.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/converter/v3/ActivationStatusConverter.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/repository/ActivationHistoryRepository.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/repository/ActivationRepository.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/repository/RecoveryCodeRepository.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/repository/SignatureAuditRepository.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/endpoint/v3/PowerAuthEndpoint.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v2/PowerAuthServiceImpl.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v3/PowerAuthService.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v3/PowerAuthServiceImpl.java, powerauth-java-server/src/main/resources/xsd/PowerAuth-3.0.xsd
Implementation of activation lookup and status update for multiple activations.
=> Activation lookup and status update

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v2/PowerAuthServiceImpl.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v3/PowerAuthServiceImpl.java
=> Fix #335: Improve transaction rollback on exception

powerauth-java-client-axis/src/main/java/io/getlime/security/powerauth/soap/axis/client/PowerAuthServiceClient.java, powerauth-java-client-spring/src/main/java/io/getlime/security/powerauth/soap/spring/client/PowerAuthServiceClient.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationServiceBehavior.java
Unfortunately these issues were found after the release because the scan ran for too long.
=> Fix #379: Fix issues found by coverity scan

pom.xml, powerauth-java-client-axis/pom.xml, powerauth-java-client-spring/pom.xml, powerauth-java-server/pom.xml, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/Application.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/converter/v3/RecoveryPukConverter.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/converter/v3/ServerPrivateKeyConverter.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v2/ActivationServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v2/EncryptionServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v2/TokenBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v2/VaultUnlockServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ApplicationServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/AsymmetricSignatureServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/EciesEncryptionBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/OfflineSignatureServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/OnlineSignatureServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/RecoveryServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/SignatureSharedServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/TokenBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/UpgradeServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/VaultUnlockServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v2/PowerAuthServiceImpl.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v3/PowerAuthServiceImpl.java, powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/VerifySignatureConcurrencyTest.java
This pull request removes the crypto provider abstraction and updates the version to `0.24.0-SNAPSHOT`.
=> Fix #382: Deprecate crypto provider abstraction

pom.xml, powerauth-java-client-axis/pom.xml, powerauth-java-client-spring/pom.xml, powerauth-java-server/pom.xml, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v2/PowerAuthServiceImpl.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v3/PowerAuthServiceImpl.java
This pull request contains hotfix for problematic transaction rollback. We have already prepared a proper fix for future server version (see PR #387), so this change just removes that rollbacks for `0.23.x` server release.
Updated server version to `0.23.2`
=> Issues/335 rollback hotfix for 0.23.x

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/converter/v3/RecoveryPukConverter.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/converter/v3/ServerPrivateKeyConverter.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v2/ActivationServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v2/EncryptionServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v2/TokenBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v2/VaultUnlockServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ApplicationServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/AsymmetricSignatureServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/CallbackUrlBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/EciesEncryptionBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/OfflineSignatureServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/OnlineSignatureServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/RecoveryServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/SignatureSharedServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/TokenBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/UpgradeServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/VaultUnlockServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/exceptions/GenericServiceException.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/exceptions/RollbackingServiceException.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/i18n/LocalizationProvider.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v2/PowerAuthServiceImpl.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v3/PowerAuthServiceImpl.java, powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/CreateApplicationTest.java
The pull request contains following improvements:
- Prepare special Exception and error handling for rollbacks
- Fix invalid rollback handling in services
- Comment each service exception with information concerning database rollbacks
- Handle `RuntimeException` properly
=> Improve rollback handling in services

pom.xml, powerauth-java-client-spring/pom.xml, powerauth-java-server/pom.xml
Besides updating the dependencies, I also finally stopped being lazy and extracted all the variables to the parent pom.xml.
=> Fix #392: Update dependencies

powerauth-java-client-axis/src/main/java/io/getlime/security/powerauth/soap/axis/client/PowerAuthServiceClient.java, powerauth-java-client-spring/src/main/java/io/getlime/security/powerauth/soap/spring/client/PowerAuthServiceClient.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v3/PowerAuthServiceImpl.java
The problem was just in the `boolean` type, the XSD and WSDL was correct.
=> Fix #402: Incompatible SOAP change in removeActivation

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v2/PowerAuthServiceImpl.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v3/PowerAuthServiceImpl.java
The logging of rollbacks should be consistent with:
https://github.com/spring-projects/spring-framework/blob/31fa1569c54649c7f3cbf7ec330e2a7232c7cd3a/spring-tx/src/main/java/org/springframework/transaction/interceptor/DefaultTransactionAttribute.java#L134
=> Fix #419: Improve logging for rollbacks

docs/Deploying-PowerAuth-Server.md, powerauth-java-server/src/main/resources/application.properties, powerauth-java-server/src/test/resources/application.properties
Changes based on Spring boot 2.2 migration guide.
=> Fix #415: Update application configuration

powerauth-java-client-axis/src/main/resources/soap/wsdl/serviceV3.wsdl, powerauth-java-client-spring/src/main/resources/soap/wsdl/serviceV3.wsdl, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/converter/v3/RecoveryPukConverter.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/converter/v3/ServerPrivateKeyConverter.java
Two minor improvements:
- Fixed WSDL formatting
- Added comments related to rollbacks in converters
=> Cleanup before release

pom.xml, powerauth-java-client-axis/pom.xml, powerauth-java-client-spring/pom.xml, powerauth-java-server/pom.xml, powerauth-java-server/src/main/webapp/META-INF/services/javax.xml.transform.TransformerFactory, powerauth-java-server/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
The pull request contains following changes:
- exclusion of problematic Xalan modules
- registration of `TransformerFactory` with Xalan from the JDK
- version upgrade to `0.22.4` for the hotfix release
=> Fix UTF-8 surrogate character issues in JBoss

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/model/TokenInfo.java
See issue for details: https://github.com/wultra/powerauth-server/issues/447
=> Fix #447: Inconsistent model classes for createToken

docs/PowerAuth-Server-1.0.0.md, docs/SOAP-Service-Methods.md, docs/sql/mysql/create_schema.sql, docs/sql/oracle/create_schema.sql, docs/sql/postgresql/create_schema.sql, powerauth-java-client-axis/src/main/java/io/getlime/security/powerauth/soap/axis/client/PowerAuthServiceClient.java, powerauth-java-client-axis/src/main/resources/soap/wsdl/serviceV3.wsdl, powerauth-java-client-spring/src/main/java/io/getlime/security/powerauth/soap/spring/client/PowerAuthServiceClient.java, powerauth-java-client-spring/src/main/resources/soap/wsdl/serviceV3.wsdl, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/controller/v3/PowerAuthController.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/ActivationFlagConverter.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/ApplicationRoleConverter.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/ApplicationRolesConverter.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/ActivationRecordEntity.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/ApplicationEntity.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/endpoint/v3/PowerAuthEndpoint.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/ServiceBehaviorCatalogue.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationFlagsServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ApplicationRolesServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ApplicationServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/OfflineSignatureServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/OnlineSignatureServiceBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/TokenBehavior.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v3/PowerAuthService.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v3/PowerAuthServiceImpl.java, powerauth-java-server/src/main/resources/xsd/PowerAuth-3.0.xsd, powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/GetApplicationDetailTest.java
This pull request adds the application role management into PowerAuth server. I also polished some parts of the activation flags implementation to unify conventions used in these two similar features.
=> Fix #298: Define "application roles"

docs/SOAP-Service-Methods.md, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/CallbackUrlBehavior.java
Updated documentation for callbacks.
=> Documentation updates for extended callbacks

pom.xml
I overlooked that there is a newer version available.
=> Update Open API Documentation version

pom.xml, powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/CreateApplicationTest.java, powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/GetApplicationDetailTest.java, powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/RecoveryPrivateKeyConverterTest.java, powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/ServerPrivateKeyConverterTest.java, powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/VerifySignatureConcurrencyTest.java
Dependency updates and migration to JUnit 5.
=> Fix #484: Upgrade Spring boot to release 2.2.9.RELEASE

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/RecoveryServiceBehavior.java
I fixed forgotten initialization of default value.
=> Fix #514: Constraint violation for postcard private key encryption

powerauth-java-server/pom.xml
Backport of Fix #626: Enable metrics for prometheus actuator
=> Update release 1.1.x

docs/PowerAuth-Server-1.3.0.md, pom.xml
Merge of the DDL and dependency updates into this feature branch.
=> Integrate changes from release 1.2.5 into auditing branch

powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/PowerAuthClient.java, powerauth-rest-client-spring/src/main/java/com/wultra/security/powerauth/rest/client/PowerAuthRestClient.java
Add alternate methods for compatibility with existing code which calls the client methods without query parameters and HTTP headers.
=> Add alternate methods for compatibility with existing code 

powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/CreateApplicationTest.java
=> Fix #706: Failing test testCreateApplicationWithDuplicateName

pom.xml, powerauth-admin/pom.xml, powerauth-client-model/pom.xml, powerauth-java-server/pom.xml, powerauth-rest-client-spring/pom.xml
=> Stop using revision property for project version

powerauth-java-server/src/main/resources/application.properties, powerauth-java-server/src/test/resources/application.properties
=> Change lock timeout from javax to jakarta

powerauth-admin/src/main/java/io/getlime/security/app/admin/configuration/WebSecurityConfig.java
See https://docs.spring.io/spring-security/reference/5.8/migration/servlet/authorization.html#switch-filter-all-dispatcher-types
=> Fix #896: Endless loop after enabling LDAP authentication in PowerAuth admin

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehavior.java
This PR removes the rest of V2 protocol support
=> Fix #958: Remove V2 protocol remnants

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/CallbackUrlBehavior.java, powerauth-rest-client-spring/src/main/java/com/wultra/security/powerauth/rest/client/PowerAuthRestClientConfiguration.java
- Change connectTimeout to Duration and handle consequence impact
=> Fix #963: Fix forgotten connectTimeout property

docs/Configuration-Properties.md, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/configuration/PowerAuthServiceConfiguration.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/CallbackUrlBehavior.java, powerauth-java-server/src/main/resources/application.properties, powerauth-java-server/src/test/resources/application.properties
Depends on https://github.com/wultra/lime-java-core/pull/200
=> Fix #651: Potential Netty memory leak when calling callbacks

.github/workflows/codeql-analysis.yml
- Input secrets to new parent codeql-analysis
=> Fix #966: Use improved codeql analysis script

docs/db/changelog/changesets/powerauth-java-server/1.4.x/20230323-add-tag-1.4.0.xml
=> Fix liquibase tag name

docs/db/changelog/changesets/powerauth-java-server/1.5.x/20230822-add-tag-1.5.0.xml, docs/db/changelog/changesets/powerauth-java-server/1.5.x/db.changelog-version.xml
=> Fix #976: Add liquibase tag 1.5.0

pom.xml
=> Fix #974: Update to non-snapshot dependencies

powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java
=> Fix ActivationServiceBehaviorTest

docs/Database-Structure.md
=> Document signature_metadata db column

powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/model/signature/SignatureDataParserTest.java
=> Reformat code in SignatureDataParserTest

pom.xml, powerauth-admin/pom.xml, powerauth-client-model/pom.xml, powerauth-java-server/pom.xml, powerauth-rest-client-spring/pom.xml
=> Fix #972: Set release version to 1.5.0

powerauth-java-server/pom.xml
=> Fix target path of filtered jboss descriptor

docs/PowerAuth-Server-0.22.0.md, docs/PowerAuth-Server-1.5.0.md, docs/WebServices-Methods.md
(cherry picked from commit 765d7f87d92733e45a1a6b37c599f4eef8540fde)
=> Fix #1068: DocuCheck Warnings (backport)

pom.xml, powerauth-admin/pom.xml, powerauth-java-server/pom.xml
=> Clean-up embed-tomcat dependencies

pom.xml, powerauth-admin/pom.xml, powerauth-java-server/pom.xml
=> Clean-up maven dependencies

docs/System-Requirements.md
(cherry picked from commit 4dbba94d4ea55385d9afebc4dc7eb647568f85b3)
=> Fix #1092: Update documentation regarding AS support (backport)

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/PowerAuthService.java
=> Keep error code of GenericServiceException for updateActivationName

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/PowerAuthService.java
Follow-up to #1107
(cherry picked from commit 38823611c422fd583a484bbea82003515fafa85a)
=> Keep error code of GenericServiceException for updateActivationName (backport)

powerauth-admin/src/main/resources/application.properties, powerauth-admin/src/main/resources/banner.txt, powerauth-java-server/src/main/resources/application.properties, powerauth-java-server/src/main/resources/banner.txt
=> Fix #1169: Custom Spring Boot Banner

pom.xml
=> Fix #1160: Update PAS 1.4.x wultra-stack dependencies for release

pom.xml
=> Fix #1236: Update Wultra dependencies to SNAPSHOT

powerauth-admin/src/main/resources/application.properties
- Exclude UserDetailsServiceAutoConfiguration
=> Fix #1245: Warning: Using generated security password

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/PowerAuthService.java
Fix #1241
Rethrow `GenericServiceException` with specific error code.
=> Fix #1241: Rethrow original GenericServiceException

docs/db/changelog/changesets/powerauth-java-server/1.4.x/20230322-init-db.xml
(cherry picked from commit 4acec34f2fa54404f5dfb8a4db0845c5380f47b4)
=> Fix #1257: Database initialization using Liquibase fails (backport)

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/repository/OperationRepository.java, powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/database/repository/OperationRepositoryTest.java, powerauth-java-server/src/test/resources/io/getlime/security/powerauth/app/server/database/repository/OperationRepositoryTest.sql
(cherry picked from commit 8b8442aa16cfbeb367382b8526b9e8357d3e13c7)
=> Fix #1308: Operation list fails on Oracle (backport)

docs/Configuration-Properties-Admin.md, docs/Configuration-Properties.md, powerauth-admin/pom.xml, powerauth-admin/src/main/resources/application.properties, powerauth-java-server/pom.xml, powerauth-java-server/src/main/resources/application.properties
(cherry picked from commit 34fa58e523b4b4c3d63acaac2845c541700e0d74)
=> Fix #1227: Add micrometer-registry-prometheus [Backport]

docs/db/changelog/changesets/powerauth-java-server/1.6.x/20231106-add-foreign-keys.xml
(cherry picked from commit c33f427ee263fb7bc72e464fd76a1a60217b41ad)
=> Fix #1376: Liquibase on MSSQL throws error do not fail on error (backport)

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/fido2/PowerAuthCryptographyService.java
=> Refactor resolveEcPoint to switch expression

powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/converter/AssertionChallengeConverter.java
This reverts commit 0da5526e7cf9273fad85719b87af80c5e231e9ba.
=> Revert "Fix #1425: FIDO2: Return operation data in a separate allowCredential item (#1427)"

powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/converter/AssertionChallengeConverter.java, powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/service/AssertionService.java, powerauth-fido2/src/test/java/com/wultra/powerauth/fido2/rest/model/converter/AssertionChallengeConverterTest.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/fido2/PowerAuthAssertionProvider.java
`AssertionChallengeConverter`'s methods were all made static and test of the methods were added.
=> Fix #1440: Add unit test for AssertionChallengeConverter

docs/System-Requirements.md
=>  Update the minimal version of WildFly to 27 to support Spring Boot 3

powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/OperationTemplateServiceBehaviorTest.java
* Random template name
(cherry picked from commit 2c873a291fffd86d55c849937dd871cc5a6d6158)
=> Fix failing OperationTemplateServiceBehaviorTest (#1466)

powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/validator/AssertionRequestValidator.java, powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/validator/RegistrationRequestValidator.java
(cherry picked from commit e3c94e8224513b8f50c0b6fa60d05329a5028392)
=> Fix #1464: Improve the error message for RP ID mismatch (backport)

powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/entity/Fido2DefaultAuthenticators.java, powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/service/AssertionService.java
(cherry picked from commit c0230c8f628dd8e9ba7ccbe4d1470e6facd789d3)
=> Fix #1461: Implement proper sanitization of credential ID (backport)

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/repository/UniqueValueRepository.java, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/replay/ReplayPersistenceService.java
(cherry picked from commit 267d08b3997b15f895ca1d1fa02c4f3dc14f3540)
=> Fix #1468: Improve performance of deleting values in table pa_unique_values (backport)

docs/Admin-Deploying-Wildfly.md, docs/Deploying-Wildfly.md, powerauth-admin/src/main/resources/application.properties, powerauth-admin/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, powerauth-java-server/pom.xml, powerauth-java-server/src/main/resources/application.properties, powerauth-java-server/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
=> Fix #1480: Improve WildFly documentation and configuration

docs/Database-Structure.md, docs/db/changelog/changesets/powerauth-java-server/1.7.x/20240115-add-columns-fido2.xml, docs/sql/mssql/migration_1.6.0_1.7.0.sql, docs/sql/oracle/migration_1.6.0_1.7.0.sql, docs/sql/postgresql/migration_1.6.0_1.7.0.sql, powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/ActivationRecordEntity.java
* Fix problem with MS SQL default value
* Make column non-null
(cherry picked from commit 0a685281621f9e2b2e35a9385c63d5e0b41eb073)
=> Fix #1538: DB migration issue (MS SQL, possible Oracle) (forwardport)

powerauth-client-model/pom.xml, powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/model/response/VerifyECDSASignatureResponse.java
=> Fix JSON (de)serialization of VerifyECDSASignatureResponse

docs/Database-Structure.md
=> Document pa_fido2_authenticator.transports

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/VaultUnlockServiceBehavior.java
=> Remove commented out code

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/task/CleaningTask.java
=> Remove superfluous transactional annotation

.gitignore, docs-private/Developer-How-To-Start.md
You can run the shell code snippets from inside IDEA. Following the tutorial should result in generating the diagram with the right tables.
=> Fix #1603: Schema diagram how to

powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/OperationServiceBehaviorTest.java
=> Fix OperationServiceBehaviorTest

docs/db/changelog/changesets/powerauth-java-server/1.8.x/20240625-add-tag-1.8.0.xml, docs/db/changelog/changesets/powerauth-java-server/1.8.x/db.changelog-version.xml
=> Fix #1584: Add liquibase tag 1.8.0

pom.xml, powerauth-admin/pom.xml, powerauth-client-model/pom.xml, powerauth-fido2-model/pom.xml, powerauth-fido2/pom.xml, powerauth-java-server/pom.xml, powerauth-rest-client-spring/pom.xml
=> Fix #1578: Set release version to 1.8.0

powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/RecoveryPrivateKeyConverterTest.java, powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/ServerPrivateKeyConverterTest.java, powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/converter/RecoveryPukConverterTest.java
An important step before the refactor
Related to #1607
=> Extend tests for encryption

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/RecoveryCodeEntity.java
(cherry picked from commit 2fa65f1ceb26c753b0fc0fe49f808dfb1683c5f6)
=> Fix #1689: Cycle in toString of RecoveryCodeEntity and ApplicationEntity (1.6.x)

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/enumeration/CommitPhase.java
=> Format JavaDoc for CommitPhase

docs/OIDC-Activation.md, docs/WebServices-Methods.md, docs/_Sidebar.md
=> Improve documentation of OIDC activation configuration

pom.xml
=> Fix #1739: Update Wultra dependencies

pom.xml, powerauth-admin/pom.xml, powerauth-client-model/pom.xml, powerauth-fido2-model/pom.xml, powerauth-fido2/pom.xml, powerauth-java-server/pom.xml, powerauth-rest-client-spring/pom.xml
(cherry picked from commit f1a31bb76206b99be9df8e7823afe32f032de5ee)
=> Fix #1705: Set release version to 1.9.0
