powerauth-java-server/pom.xml
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/repository/ActivationRepository.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/repository/SignatureAuditRepository.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/AuditingServiceBehavior.java
powerauth-java-server/src/main/resources/application.properties
powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/VerifySignatureConcurrencyTest.java

* Fix #32: Database deadlock when multiple PA signatures are validated at the same time - the problem was fixed by introducing a row level PESSIMISTIC_WRITE DB lock and increasing lock timeout  
* Fix ordering of signature audit records - concurrent requests occurring within same second were ordered incorrectly in MySQL database, ordering is now done by record ID which has no such problems
* Added test for MySQL deadlock. The test is disabled to avoid failing Travis builds due to missing MySQL database.

Fix #32: Database deadlock when multiple PA signatures are validated at the same time

---

pom.xml
powerauth-java-client-axis/pom.xml
powerauth-java-client-spring/pom.xml
powerauth-java-server/pom.xml

In order to prepare for the release, we should update library dependencies.

Fix #45: Update library dependencies

---

powerauth-java-client-axis/src/main/java/io/getlime/security/powerauth/soap/axis/client/PowerAuthServiceClient.java
powerauth-java-client-axis/src/main/resources/soap/wsdl/service.wsdl
powerauth-java-client-spring/src/main/java/io/getlime/security/powerauth/soap/spring/client/PowerAuthServiceClient.java
powerauth-java-client-spring/src/main/resources/soap/wsdl/service.wsdl
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/controller/PowerAuthController.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/endpoint/PowerAuthEndpoint.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/PowerAuthService.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/PowerAuthServiceImpl.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/SignatureServiceBehavior.java
powerauth-java-server/src/main/resources/xsd/PowerAuth-2.0.xsd

Note that I use "data" in requests  and "offlineData" in responses to differentiate incoming and outgoing data during signature payload construction. The "offlineData" now contains all data that is required to construct the QR code. If you have a better idea how to name this input/output data, let me know.

Fix #71: Implement personalized and non-personalized variants of createOfflineSignaturePayload

---

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/converter/ServerPrivateKeyConverter.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/KeyEncryptionMode.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/ActivationRecordEntity.java
powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/ServerPrivateKeyConverterTest.java

Avoid using PBKF2 function when deriving secret key to improve performance, renamed related encryption mode

Application level record encryption - performance optimization

---

powerauth-java-server/pom.xml

Exclude geronimo-javamail because of issues found in OWASP report

Fix #154: Exclude ehcache Spring WS security dependency

---

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/controller/RESTControllerAdvice.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/converter/KeyValueMapConverter.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/converter/ServerPrivateKeyConverter.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/PowerAuthServiceImpl.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/CallbackUrlBehavior.java

Use SLF4J logger obtained via logger factory, instead of JULI logger obtain in place
Use generic string instead of null when logging fallback exceptions
Fix placeholders for SLF4J, use placeholders instead of string concatenation where possible

Fix #166: Improve the logging code clarity and performance

---

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/SignatureServiceBehavior.java

Invalid verification should return real activation status not only REMOVED, to recognize BLOCKED state

Invalid state response for signature verification

---

powerauth-java-client-axis/src/main/java/io/getlime/security/powerauth/soap/axis/client/PowerAuthServiceClient.java
powerauth-java-client-axis/src/main/resources/soap/wsdl/service-v3.wsdl
powerauth-java-client-spring/src/main/java/io/getlime/security/powerauth/soap/spring/client/PowerAuthServiceClient.java
powerauth-java-client-spring/src/main/resources/soap/wsdl/service-v3.wsdl
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/EciesEncryptionBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/TokenBehavior.java
powerauth-java-server/src/main/resources/xsd/PowerAuth-3.0.xsd

As agreed with @hvge, `ephemeralPublicKey` will be used instead of `ephemeralKey` in SOAP interfaces.

Use ephemeralPublicKey instead of ephemeralKey

---

docs/sql/mysql/create_schema.sql
docs/sql/oracle/create_schema.sql
docs/sql/postgresql/create_schema.sql
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/EciesEncryptionBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/TokenBehavior.java

Fix of two minor issues:
- #192: Crypto 3.0: Activation code should not be required in database
- #194: Crypto 3.0: Use application secret for ECIES in Base64 form #194

Fix #192: Crypto 3.0: Activation code should not be required in database

---

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v2/ActivationServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/AsymmetricSignatureServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/TokenBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/VaultUnlockServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v2/PowerAuthServiceImpl.java

Following issues were found by automated tests:
- NPE in `verifyECDSASignature`
- 500 error when removed token was validated (we should rather return token not valid response)
- database error when vault unlock reason was too long
- application version is not checked in `initActivation` (this is OK, I just added a comment it is checked later)

Fix #198: Crypto 3.0: Improve error handling and input validation based on automated test results

---

powerauth-java-client-axis/src/main/java/io/getlime/security/powerauth/soap/axis/client/PowerAuthServiceClient.java
powerauth-java-client-spring/src/main/java/io/getlime/security/powerauth/soap/spring/client/PowerAuthServiceClient.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v2/ActivationServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/model/ServiceError.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v2/PowerAuthServiceImpl.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v3/PowerAuthServiceImpl.java
powerauth-java-server/src/main/resources/i18n/errors.properties

This PR introduces custom activation implementation on PowerAuth server.
I added the timestamp expiration check which was previously missing to v2 version, too.

Fix #186: Crypto 3.0: Custom activation

---

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/repository/ActivationRepository.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationServiceBehavior.java

The uniqueness check is reverted to version 2 of crypto (the condition is unique `activationIdShort` per application instead of unique `activationCode` per application).

Fix #227: InitActivation should use version 2 duplicity check when checking for duplicates

---

powerauth-java-client-axis/pom.xml
powerauth-java-client-axis/src/main/resources/soap/wsdl/service.wsdl
powerauth-java-client-spring/src/main/resources/soap/wsdl/service.wsdl
powerauth-java-server/src/main/resources/xsd/PowerAuth-2.0.xsd

This pull request backports the fix of WSDL from issue https://github.com/wultra/powerauth-server/issues/228 for vault unlock due to Axis client error when vault unlock fails.
The version of `powerauth-java-client-axis` project is increased to `0.19.1`. I fixed the WSDL and XSD in all projects, however I didn't increase other project versions because we only need to release the Axis client.

 Fix #249: Backport fix of WSDL for vault unlock error state in Axis client

---

powerauth-java-server/src/main/resources/application.properties

The workaround is no longer required.

Fix #254: Remove workaround for follow-on-locking in Hibernate

---

docs/PowerAuth-Server-0.21.0.md
docs/sql/mysql/create_schema.sql

The original index definition failed in Docker while it worked fine on my newer version of MySQL.

Fix #278: Use case sensitive index definition for MySQL

---

pom.xml

The issue is finally fixed in Spring boot `2.1.4`.

Fix #276: Startup issue on Wildfly with Java 11 and Spring Boot 2.1.2

---

docs/Deploying-PowerAuth-Server.md
docs/Deploying-Wildfly.md
docs/Installing-Bouncy-Castle.md
docs/_Sidebar.md
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/configuration/PowerAuthServiceConfiguration.java
powerauth-java-server/src/main/resources/application.properties
powerauth-java-server/src/main/webapp/WEB-INF/jboss-deployment-structure.xml

This pull request adds the deployment descriptor for JBoss / Wildfly and activates the "ext" profile to allow overriding of `application properties`. It also includes documentation for deploying on JBoss / Wildfly.

Fix #292: Add jboss-deployment-structure.xml file

---

docs/SOAP-Service-Methods.md
powerauth-java-client-axis/src/main/java/io/getlime/security/powerauth/soap/axis/client/PowerAuthServiceClient.java
powerauth-java-client-axis/src/main/resources/soap/wsdl/service-v3.wsdl
powerauth-java-client-spring/src/main/java/io/getlime/security/powerauth/soap/spring/client/PowerAuthServiceClient.java
powerauth-java-client-spring/src/main/resources/soap/wsdl/service-v3.wsdl
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/RecoveryServiceBehavior.java
powerauth-java-server/src/main/resources/xsd/PowerAuth-3.0.xsd

This pull request contains following changes:
- Document SOAP interface for recovery codes
- Update SOAP interface method names to exclude base64 word
- Use `Base64` as one word instead of `Base 64`

Document SOAP interface for recovery codes

---

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationServiceBehavior.java

I forgot about the reset of failed attempts.

Fix #310: Reset failed attempts for recovery code when PUK is valid

---

docs/SOAP-Service-Methods.md
powerauth-java-client-axis/src/main/java/io/getlime/security/powerauth/soap/axis/client/PowerAuthServiceClient.java
powerauth-java-client-axis/src/main/resources/soap/wsdl/service-v3.wsdl
powerauth-java-client-spring/src/main/java/io/getlime/security/powerauth/soap/spring/client/PowerAuthServiceClient.java
powerauth-java-client-spring/src/main/resources/soap/wsdl/service-v3.wsdl
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/RecoveryServiceBehavior.java
powerauth-java-server/src/main/resources/xsd/PowerAuth-3.0.xsd

Update of SOAP interface so that PowerAuth Admin can configure the `allowMultipleRecoveryCodes` option.

Add configuration of allowMultipleRecoveryCodes to SOAP interface

---

pom.xml
powerauth-java-server/pom.xml

The resolution is:
- `tomcat-embed-core` is upgraded transitively by upgrading `spring-boot-starter-parent`
- `ehcache` is excluded as in previous release
- `geronimo-javamail` is excluded as in previous release
- issues in Spring boot security are related to Spring Framework `5.0.5`, see: https://pivotal.io/security/cve-2018-1258
- `jackson-databind` upgrade is risky, there is no version of `Spring Boot` released with fixed version, moreover the advisory does not apply to current usage (it requires `default typing` enabled and is only applicable to `MySQL`)

Fix #319: Resolve advisories reported by OWASP check

---

powerauth-java-server/src/main/webapp/WEB-INF/jboss-deployment-structure.xml

This pull request excludes the problematic `org.apache.xalan` module together with the related `org.apache.xerces` module.
The Xalan library distributed with JBoss contains following bug:
https://issues.apache.org/jira/browse/XALANJ-2617
This bug has never been fixed in Xalan sources, although there were several attempts to fix it, such as this one:
https://github.com/apache/xalan-j/pull/4
Note that the pull request was done on a fork of original Xalan sources because the original project does not seem to be actively maintained.
Thus, the issue remains open in Wildfly/JBoss and causes problems when UTF-8 characters such as 🙎🏾‍♂️are used in PowerAuth SOAP responses:
https://issues.redhat.com/browse/WFLY-10166
https://issues.redhat.com/browse/JBEAP-14542
The bug is fixed in the JAXP …

Fix #425: Exclude org.apache.xalan module for JBoss

---

pom.xml
powerauth-java-client-axis/pom.xml
powerauth-java-client-spring/pom.xml
powerauth-java-server/pom.xml
powerauth-java-server/src/main/webapp/META-INF/services/javax.xml.transform.TransformerFactory

The following fix of `TransformerFactory` will avoid the UTF-8 surrogate character transformation bug in Xalan when another factory is set in the application server.

Fix #432: Configure TransformerFactory for JBoss

---

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ApplicationServiceBehavior.java

Fixed new exceptions thrown when random generator is not initialized due to missing or invalid Bouncy Castle library initialization

Fix exceptions related to incorrect crypto provider initialization

---

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/repository/ActivationRepository.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v3/PowerAuthServiceImpl.java

It is not possible to use `null` values in dates for Postgres without a cast in JPQL. A cast could lead to incompatibilities, so I use minimum and maximum values for dates instead. I will test the `1.1.9999` date on other databases, too, it should be valid based on the SQL standard.

Fix #520: Cannot determine datatype error in JPA for Postgres

---

docs/Configuring-SOAP-Client-for-Axis2.md
docs/Configuring-SOAP-Client-for-Spring.md
docs/Deploying-PowerAuth-Server.md
docs/Offline-Signatures.md
docs/PowerAuth-Server-0.21.0.md
docs/PowerAuth-Server-0.22.0.md
docs/PowerAuth-Server-0.23.0.md
docs/PowerAuth-Server-0.24.0.md
docs/Readme.md
docs/SOAP-Client-Library-Usage.md
docs/WebServices-Client.md
docs/WebServices-Method-Compatibility.md
docs/WebServices-Methods.md
docs/_Sidebar.md

Improvement of the REST documentation, putting it on par with SOAP. For sure we will need to improve the documentation even further once we drop SOAP.

Fix #516: Improve documentation for REST API

---

powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/PowerAuthClient.java
powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/model/enumeration/CallbackUrlType.java
powerauth-rest-client-spring/src/main/java/com/wultra/security/powerauth/rest/client/PowerAuthRestClient.java

The missing URL type was causing an exception on server when running tests.

Add callback URL type to REST client

---

powerauth-java-server/pom.xml
powerauth-rest-client-spring/pom.xml

This change should resolve any future questions about the Log4J dependencies included in Spring logging.

Fix #641: Exclude log4j-api dependency

---

powerauth-rest-client-spring/src/main/java/com/wultra/security/powerauth/rest/client/PowerAuthRestClient.java

Improved logging for following cases:
- PowerAuth service is not accessible (e.g. port is blocked)
- PowerAuth service is not available (HTTP status 404)

Fix #664: Improve logging in PowerAuth REST client

---

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/configuration/PowerAuthAuditConfiguration.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/configuration/WebServiceConfig.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/AuditingServiceBehavior.java

The problem was that the configuration was done in `WebServiceConfig extends WsConfigurerAdapter` which caused following issue:
```
Bean 'databaseAuditWriter' of type [com.wultra.core.audit.base.database.DatabaseAuditWriter] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
```
Due to this issue the task was not scheduled. Moving configuration to a new configuration class solves the issue.

Fix scheduling for PowerAuth auditing

---

pom.xml
powerauth-client-model/pom.xml
powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/PowerAuthClient.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/configuration/InterceptorConfiguration.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/interceptor/HttpHeaderInterceptor.java
powerauth-java-server/src/main/resources/application.properties
powerauth-rest-client-spring/src/main/java/com/wultra/security/powerauth/rest/client/PowerAuthRestClient.java
powerauth-rest-client-spring/src/main/java/com/wultra/security/powerauth/rest/client/PowerAuthRestClientConfiguration.java

- Fix #673: Allow specifying query parameters and HTTP headers in REST client calls
- Fix #684: Add support for logging using correlation ID with MDC

Allow custom HTTP headers in REST client, log correlation ID

---

powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/PowerAuthClient.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v2/ActivationServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v3/PowerAuthServiceImpl.java
powerauth-java-server/src/main/resources/xsd/PowerAuth-3.0.xsd
powerauth-rest-client-spring/src/main/java/com/wultra/security/powerauth/rest/client/PowerAuthRestClient.java

The pull request addresses two areas:
- We inherit activation flags when creating a new operation using recovery codes that are linked to an activation.
- We allow specifying if recovery codes should be created using `prepareActivation`/`createActivation`/`createActivationUsingRecoveryCode` call.
The reason is the following:
- When we have activation that uses flags to mark it is "partially completed", we must make sure descendant activation is also marked like this.
- When recovering activation on old mobile client versions that does not support "partially completed" activation flag yet, we want to have a mechanism in place to assure that the "partially completed" activation does not create recovery codes.

Fix #710: Inherit activation flags when recovering activation

---

docs/PowerAuth-Server-1.4.0.md
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/TokenBehavior.java
powerauth-java-server/src/main/resources/xsd/PowerAuth-3.0.xsd

Unify response data and logic for signature verification and token verification.

Fix #764: Return activation status in ValidateTokenResponse

---

powerauth-admin/src/main/java/io/getlime/security/app/admin/converter/SignatureAuditItemConverter.java
powerauth-admin/src/main/java/io/getlime/security/app/admin/converter/SignatureDataConverter.java
powerauth-admin/src/main/java/io/getlime/security/app/admin/util/QRUtil.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/converter/v3/RecoveryPrivateKeyConverter.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/converter/v3/RecoveryPukConverter.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/converter/v3/ServerPrivateKeyConverter.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v2/ActivationServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v2/EncryptionServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v2/TokenBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v2/VaultUnlockServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ApplicationServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/AsymmetricSignatureServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/AuditingServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/EciesEncryptionBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/OfflineSignatureServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/RecoveryServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/SignatureSharedServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/TokenBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/UpgradeServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/VaultUnlockServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v3/PowerAuthServiceImpl.java
powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/RecoveryPrivateKeyConverterTest.java
powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/ServerPrivateKeyConverterTest.java
powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/VerifySignatureConcurrencyTest.java

Use `java.util.Base64` instead of `com.google.common.io.BaseEncoding#base64()`.
See https://rules.sonarsource.com/java/tag/java8/RSPEC-4738

Fix #858: Prefer Java 8 APIs over Guava

---

powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/model/response/ConfirmRecoveryCodeResponse.java
powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/model/response/CreateActivationResponse.java
powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/model/response/CreateTokenResponse.java
powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/model/response/PrepareActivationResponse.java
powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/model/response/RecoveryCodeActivationResponse.java
powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/model/response/StartUpgradeResponse.java
powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/model/response/VaultUnlockResponse.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/RecoveryServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/TokenBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/UpgradeServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/VaultUnlockServiceBehavior.java

This PR fixes two major problems in ECIES 3.2 implementation:
- Do not use nonce in encrypted response (#950)
- Do not return `ephemeralPublicKey` in encrypted responses (#938)

Broken ECIES 3.2

---

docs/PowerAuth-Server-1.5.0.md
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/PowerAuthService.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/EciesEncryptionBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/RecoveryServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/TokenBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/UpgradeServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/VaultUnlockServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/replay/ReplayVerificationService.java
powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/VerifySignatureConcurrencyTest.java

This PR replaces usage of low level ECIES with a new general encryptor facility introduced in wultra/powerauth-crypto#493 
This PR will fix:
- #957
- #956
TODO:
- We have to properly check usage of replay verification service. It's clear that such service store data to database in case that entry is new (e.g. there's no replay attack), so all our comments about transaction rollback in exceptions appears to be inaccurate.
- Documentation

Use general encryptor for E2EE

---

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/RecoveryCodeEntity.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehavior.java
powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java

The encrypted payload represents ActivationLayer2Request.class, which contains:
- devicePublicKey (expected)
- activationOtp, platform (have logic based on null value later)
- non-specific activationName, extras, deviceInfo
Test case was created to replicate the issue and the issue was solved by checking of presence of the devicePublicKey, which is the only attribute passed directly to a method without being checked.

Fix #762: Insufficient input validation in activation prepare endpoint

---

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/CallbackUrlBehavior.java
powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/CallbackUrlBehaviorTest.java
powerauth-java-server/src/test/resources/io/getlime/security/powerauth/app/server/service/behavior/tasks/CallbackUrlBehaviorTest.sql

Fix #1100:
If `applicationId` from the request does not match the `applicationId` paired with the callback, behave like the callback does not exist at all.

Fix #1100: Application check in update callback api

---

docs/WebServices-Methods.md

Fix #1097
Added `type` attribute to create request, update response and list response of the Callback url API.

Fix #1097: Edit callback API documentation

---

pom.xml
powerauth-java-server/pom.xml
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/ActivationHistoryEntity.java
powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/database/model/entity/ActivationHistoryEntityTest.java

Fix equals and hashCode of ActivationHistoryEntity

---

pom.xml
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/configuration/PowerAuthServiceConfiguration.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/OfflineSignatureServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/OnlineSignatureServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/SignatureSharedServiceBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/model/signature/SignatureData.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/v3/PowerAuthServiceImpl.java
powerauth-java-server/src/main/resources/application.properties
powerauth-java-server/src/main/resources/xsd/PowerAuth-3.0.xsd
powerauth-java-server/src/test/resources/application.properties

Cherry- picked from commit b4b583e149e2aeccc54dacfb8e3547218c146a5c and f704672a695b4da600c7f5974d476bd2bfd25ab0 (fixes test), are predecessors of https://github.com/wultra/powerauth-server/pull/939 backport

Fix #832: Allow shorter OTP for offline signatures (backport)

---

docs/db/changelog/changesets/powerauth-java-server/1.7.x/20240212-application-config.xml
docs/sql/mssql/migration_1.6.0_1.7.0.sql
docs/sql/oracle/migration_1.6.0_1.7.0.sql
docs/sql/postgresql/migration_1.6.0_1.7.0.sql

Fix column name pa_application_config.config_key in db scripts

---

powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/model/entity/fido2/AllowCredentials.java
powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/model/request/fido2/AssertionChallengeRequest.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/fido2/PowerAuthAssertionProvider.java

Issue https://github.com/wultra/powerauth-server/issues/1374 does not reflect changes made to requests/responses to client model.
There was also an error `ArrayList cannot be cast to class Set` while deserialising additional data to set, which was fixed by using list instead.

Fix #1407: Reflect fido2 changes in client model

---

pom.xml

Fix #1410 by downgrading `springdoc-openapi` dependency back to 2.3.0 for now.

Fix #1410: Swagger not shown correctly

---

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/fido2/PowerAuthRegistrationProvider.java
powerauth-java-server/src/test/java/com/wultra/powerauth/fido2/Fido2AuthenticatorTest.java

I switched the AAGUID configuration to UUID, it was incorrectly expected as raw bytes.

Fix #1417: FIDO2: Invalid AAGUID format in configuration of fido2_aaguids_allowed

---

powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/converter/AssertionChallengeConverter.java

Added Base64 encoding for the operation data.

Fix #1425: FIDO2: Return operation data in a separate allowCredential item

---

powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/model/entity/fido2/AuthenticatorParameters.java
powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/model/request/fido2/AssertionVerificationRequest.java
powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/model/request/fido2/RegistrationRequest.java
powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/entity/AuthenticatorParameters.java
powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/request/AssertionVerificationRequest.java
powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/request/RegistrationRequest.java

Although I found this in [level 3 spec](https://w3c.github.io/webauthn/#iface-pkcredential) only, the `authenticatorAttachment` can be null in both ceremonies. Which is also supported by the [taken test](https://github.com/wultra/powerauth-server/issues/1436).
This test also found out there was missing a cascade validation of parameters class in registration request and so the nested validation annotations were without effect.

Fix #1436: FIDO test app Opera browser - authenticatorAttachment error

---

powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/converter/AssertionChallengeConverter.java
powerauth-fido2/src/test/java/com/wultra/powerauth/fido2/rest/model/converter/AssertionChallengeConverterTest.java

(cherry picked from commit 7cfbae3a22d0f220abd2e253ab8d53931475da3a)

Fix #1458: FIDO2: Concat operation data to credentialId (backport)

---

powerauth-fido2-model/src/main/java/com/wultra/security/powerauth/fido2/model/entity/Credential.java
powerauth-fido2-model/src/main/java/com/wultra/security/powerauth/fido2/model/response/AssertionChallengeResponse.java
powerauth-fido2-model/src/main/java/com/wultra/security/powerauth/fido2/model/response/RegistrationChallengeResponse.java
powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/converter/AssertionChallengeConverter.java
powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/converter/RegistrationChallengeConverter.java
powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/entity/AssertionChallenge.java
powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/entity/RegistrationChallenge.java
powerauth-fido2/src/test/java/com/wultra/powerauth/fido2/rest/model/converter/AssertionChallengeConverterTest.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/fido2/PowerAuthRegistrationProvider.java
powerauth-java-server/src/test/java/com/wultra/powerauth/fido2/Fido2AuthenticatorTest.java

- `RegistrationChallengeResponse` now contains `excludeCredentials`, which is a list of existing credentials.
- `AllowCredentials` data class was renamed to `Credential` to serve both - allowCredential and excludeCredential lists. This has to be reflected on the client side.

Fix #1502: FIDO2: Return excludeCredentials in RegistrationChallenge

---

.github/workflows/scp-deploy.yml

The scp-deploy workflow fails now because of changes in BC dependencies.

Fix #1505: Edit scp-deploy workflow to use internal repo

---

powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/model/entity/fido2/Credential.java
powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/model/response/fido2/AssertionChallengeResponse.java
powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/model/response/fido2/RegistrationChallengeResponse.java
powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/converter/AssertionChallengeConverter.java
powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/converter/RegistrationChallengeConverter.java
powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/entity/AssertionChallenge.java
powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/entity/Credential.java
powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/entity/RegistrationChallenge.java
powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/response/AssertionChallengeResponse.java
powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/response/RegistrationChallengeResponse.java
powerauth-fido2/src/test/java/com/wultra/powerauth/fido2/rest/model/converter/AssertionChallengeConverterTest.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/fido2/PowerAuthRegistrationProvider.java
powerauth-java-server/src/test/java/com/wultra/powerauth/fido2/Fido2AuthenticatorTest.java

Because of breaking changes in project structure, this backport is not a single cherry pick

Fix #1502: FIDO2: Return excludeCredentials in RegistrationChallenge (backport)

---

docs/Configuration-Properties.md
docs/Migration-Instructions.md
docs/PowerAuth-Server-1.8.0.md
docs/db/changelog/changesets/powerauth-java-server/1.8.x/20240424-index-expire-status.xml
docs/db/changelog/changesets/powerauth-java-server/1.8.x/db.changelog-version.xml
docs/db/changelog/changesets/powerauth-java-server/db.changelog-module.xml
docs/sql/mssql/migration_1.7.0_1.8.0.sql
docs/sql/oracle/migration_1.7.0_1.8.0.sql
docs/sql/postgresql/migration_1.7.0_1.8.0.sql
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/configuration/PowerAuthServiceConfiguration.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/repository/OperationRepository.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/CallbackUrlBehavior.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/OperationServiceBehavior.java

Changes:
1. Reordered columns in `pa_operation_status_exp` index: `pa_operation(timestamp_expires, status) -> pa_operation(status, timestamp_expires)`. Now the index is used during the query for expired pending operations.
2. Scheduled job to expire pending operation now sets as expired 100 operations only. This number is configurable via a new property.
3. CallbackUrl entities are no longer fetched via explicit repository call, but via getter on the entity.

Fix #1482: Optimization: Operation expiration optimization

---

docs/PowerAuth-Server-1.8.0.md
docs/db/changelog/changesets/powerauth-java-server/1.8.x/20240517-fido2-authenticator-transports.xml
docs/db/changelog/changesets/powerauth-java-server/1.8.x/db.changelog-version.xml
docs/sql/mssql/migration_1.7.0_1.8.0.sql
docs/sql/oracle/migration_1.7.0_1.8.0.sql
docs/sql/postgresql/migration_1.7.0_1.8.0.sql
powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/database/entity/Fido2AuthenticatorEntity.java
powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/database/entity/converter/ListToStringConverter.java
powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/converter/AssertionChallengeConverter.java
powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/converter/RegistrationChallengeConverter.java
powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/service/Fido2AuthenticatorService.java
powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/service/model/Fido2Authenticator.java
powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/service/model/Fido2DefaultAuthenticators.java
powerauth-fido2/src/test/java/com/wultra/powerauth/fido2/rest/model/converter/AssertionChallengeConverterTest.java
powerauth-fido2/src/test/java/com/wultra/powerauth/fido2/rest/model/converter/RegistrationChallengeConverterTest.java
powerauth-fido2/src/test/java/com/wultra/powerauth/fido2/service/Fido2AuthenticatorServiceTest.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/fido2/PowerAuthAssertionProvider.java
powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/fido2/PowerAuthRegistrationProvider.java

A new column `transports` has been added to the `pa_fido2_authenticator` table, which values is used during the allow/exclude credential list build as a fallback in case a browser failed to provide transport hints during the registration ceremony.
Effect on **non-Wultra authenticators**:
- If the DB column is not set or contains empty list, there is no behaviour changes compared to the current version.
- If the DB column contains non-empty list, the list will be used in case a browser did not provide transport hints during the registration ceremony.
Effect on **Wultra authenticator**:
- If the DB column for WAU record is not set or contains empty list, `["usb"]` will be used in case a browser did not provide transport hints during the registration ceremony.
- If the DB column for WAU …

Fix #1517: FIDO2: Enforce USB transport hint for WAU authenticators

---

powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/converter/AssertionChallengeConverter.java

(cherry picked from commit d66f88fb297aa504b235c22ca5131f814956ea4b)

Fix #1529: FIDO2: Missing external ID in activation (backport)

---

powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/OperationServiceBehavior.java
powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/OperationServiceBehaviorTest.java
powerauth-java-server/src/test/resources/io/getlime/security/powerauth/app/server/service/behavior/tasks/OperationServiceBehaviorTest.sql

* Fix #1560: Create Operation does not return proximity OTP
Co-authored-by: Zdeněk Černý <zdenek.cerny@wultra.com>
(cherry picked from commit e17f6f6139b7a08824279514bc98743dfc87e7d7)

Fix #1560: Create Operation does not return proximity OTP (backport)

---

powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/task/Fido2CleaningTask.java

It fixes the error: `lockAtLeastFor is longer than lockAtMostFor for lock 'evictFido2AuthenticatorCacheTask'`
Cleaning local cache, no need to lock the job across the whole cluster.
A follow-up to #1532

Remove scheduler lock from Fido2CleaningTask

---

powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/converter/serialization/Base64UrlToStringDeserializer.java
powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/entity/CollectedClientData.java
powerauth-fido2/src/test/java/com/wultra/powerauth/fido2/rest/model/converter/serialization/CollectedClientDataDeserializerTest.java

Challenge is encoded to Base64Url on the browser level. The encoded challenge is then encapsulated to the [Collected Client Data structure](https://www.w3.org/TR/webauthn-3/#dictionary-client-data), which hash is later signed by the authenticator. Base64Url decoding should be applied on the challenge during the CollectedClientData deserialization.

Fix #1644: Investigate error on Base64 decoding in challenge

---

powerauth-client-model/pom.xml

Limit client-model dependency from starter-validation to hibernate-validator only to avoid tomcat-embed-el transient dependency.
A follow-up to #1679

Limit client-model dependency from starter-validation to hibernate-validator

---

powerauth-admin/src/main/java/io/getlime/security/app/admin/controller/ApplicationController.java
powerauth-admin/src/main/webapp/WEB-INF/jsp/applicationDetail.jsp
powerauth-admin/src/main/webapp/WEB-INF/jsp/callbackCreate.jsp
powerauth-admin/src/main/webapp/WEB-INF/jsp/callbackUpdate.jsp
powerauth-client-model/src/main/java/com/wultra/security/powerauth/client/PowerAuthClient.java
powerauth-rest-client-spring/src/main/java/com/wultra/security/powerauth/rest/client/PowerAuthRestClient.java

Update PA Admin Console and PA Client to reflect changes in Callback Management API (3 new attributes).

Fix #1684: Update Client and Admin Console

---

powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/CallbackUrlBehaviorTest.java

After merging https://github.com/wultra/powerauth-server/pull/1728 a test failure occured in `CallbackUrlBehaviorTest`.
Some test from `CallbackUrlBehaviorTest` could fail because of background scheduled task are calling mocked `CallbackUrlEventService`. Avoid running the scheduled task by mocking also the `CleaningTask`

Fix #1722: Fix CallbackUrlBehaviorTest
